### ISSUE TITLE
Multi-button macros

### ISSUE THREAD

**Issue by jhpgcj** [libretro/geolith-libretro#1]
Hi, thanks for porting geolith to libretro. So far, it's working like a charm. However, I ask: is there any way to add multi-button macros, like the FBNeo core or some older Neo Geo emulators?

In practice, I mean mapping actions like A+B, B+C, A+B+C (and so on) to a single retropad button.

**Comment by carmiker** [comment]
Yes, there is certainly a way. The question is what to assign them to. There are 10 possible combinations, so I can use 2 triggers and 8 analog axis directions perhaps.

**Comment by jhpgcj** [comment]
They don't need to be all mapped out of the box, having the possibility to manually map them is enough. However, from my experience, the top 4 most used are:

- A+B
- C+D
- A+B+C
- B+C
(I think there are a couple of games that use B+C+D, but I might be wrong, need to check this further).

If you'd like to automap them, my suggestion would be using L1/L2/R1/R2, for they're easier and more practical to reach during gameplay. Since Geolith is more focused on AES, you could map "coin" and "test" to L3/R3, which are less used.

Thanks for looking into the issue!

**Comment by carmiker** [comment]
I've thought about changing the defaults, but I am also considering the experience when people are using the 8bitdo Neo Geo controller: https://www.8bitdo.com/neogeo-wireless-controller/
Mine will arrive soon, so I'll be able to test what works best with this in all modes.

**Comment by jhpgcj** [comment]
> but I am also considering the experience when people are using the 8bitdo Neo Geo controller: https://www.8bitdo.com/neogeo-wireless-controller/

Makes sense. If you can't reach a solution for all controllers, then you could just add the option and leave it to the user to map macros how (and if) they want it.

**Comment by carmiker** [comment]
I've made the change.

L1: C+D
R1: A+B
L2: B+C+D
R2: A+B+C

Select will insert coins in MVS mode, or act as a proper Select button in AES mode (this follows for the mode used in Unibios, where the Select button inserts coins in arcade mode).

This is the exact same layout as FinalBurn Neo uses, and people seem to be happy with that, so it seems like a safe way to do it. It also works nicely using my 8bitdo Neo Geo controller.

**Comment by jhpgcj** [comment]
Tested it. Works perfectly, thanks! However, if you're setting the limit of only 4 macros, then I'd like to suggest replacing B+C+D for B+C, since the latter is much more useful and widely used (like in the whole Fatal Fury, Art of Fighting and Samurai Shodown series, plus others like Savage Reign and Ninja Master's). Not to say B+C+D isn't used (it's just rarer), but it's easier to have a macro for B+C and also pressing D, instead of turning the macro useless for games which only require B+C.

Forgive me for the inconvenience.

**Comment by carmiker** [comment]
You've sold me on the change. It's pushed.

**Comment by jhpgcj** [comment]
Tested it. Everything is working perfectly. I shall close the issue. Thanks for your hard work, Geolith is already a very fine and useful core.

**Comment by barbudreadmon** [comment]
>This is the exact same layout as FinalBurn Neo uses, and people seem to be happy with that

More like we can't switch betwen different macros everytime someone is showing his discontent with the current ones. 
See https://docs.libretro.com/library/fbneo/#why-is-my-favorite-combo-button-not-available

**Comment by jhpgcj** [comment]
> > This is the exact same layout as FinalBurn Neo uses, and people seem to be happy with that
> 
> More like we can't switch betwen different macros everytime someone is showing his discontent with the current ones. See https://docs.libretro.com/library/fbneo/#why-is-my-favorite-combo-button-not-available

Bro, take it easy. Don't need to get so worked up over my suggestion, to the point of coming over to a different repo to complain, I didn't mean to offend or anything. If you didn't like it, just say "nah, I won't do it", but don't try to make drama by saying in the FAQ "no more discussion or I'll remove them". That's a very childish thing to do. If it's bothering you that much, just remove the macros all together, not that it will do your emulator any good. Just be mindful that there are rationale over any choice, and setting things in stone because of a single event of the past in which few people participated is one reason there might be still people suggesting changes.

**Comment by carmiker** [comment]
The macros in place for Geolith will remain as they are today for the forseeable future. I think we have gotten the value out of this conversation at this point. If there is ever an option to declare more buttons and map them after the fact, the discussion can be reopened.
