### ISSUE TITLE
Lagging 

### ISSUE THREAD

**Issue by RainbowShatter** [libretro/geolith-libretro#10]
Hello! I am quite new to this place and I want to know how to make geolith lag WAAAAY less, it runs at 0.5x speed because of the unbearable lag when I try to play Waku Waku 7 

I am running :
- the correct BIOS files
- all of the settings set to as fast as it can

can someone help me please

**Comment by SRC267** [comment]
Are you using Vulkan as your video driver in RetroArch? Switch to it from gl, should be in Settings > Video > Output

**Comment by carmiker** [comment]
What hardware/OS are you using?

**Comment by RainbowShatter** [comment]
i forgot to mention that i run android

**Comment by carmiker** [comment]
In that case, I am going to assume it's due to weak hardware. Since this is an accuracy focused emulator, it can be a little bit more demanding. Performance optimization is on the todo list, but first I want to get Neo Geo CD emulated.

**Comment by RainbowShatter** [comment]
mine is a Samsung A51, so i think that's the case, I'm going to make this issue open just for some other updates

**Comment by RainbowShatter** [comment]
> Are you using Vulkan as your video driver in RetroArch? Switch to it from gl, should be in Settings > Video > Output

i am using vulkan but it keeps lagging in the same way

**Comment by RainbowShatter** [comment]
and i never tried Geolith on my Linux Machine, maybe it works there
