### ISSUE TITLE
Fix for RTC bug which results in green garbage output during the earliest boot stage

### ISSUE THREAD

**Issue by mrdc** [libretro/geolith-libretro#9]
Hello!

I’ve noticed the green glitched output during the earliest boot when Neo-Geo MVS is used.
![IMG_2886](https://github.com/user-attachments/assets/0cce018a-3572-423f-9c32-d31f8ee1d22c)

The same issue applies to FBNeo. After a brief research, I’ve found this info:

>A freeze at startup on the shown screen (with no cyclic reset) is caused by the RTC not outputing a time pulse at all.
The system ROM doesn't give a CALENDAR ERROR in this particular case because of a programming oversight.

Source: https://wiki.neogeodev.org/index.php?title=Calendar_freeze

Is this bug applies to the real hardware, so emulators replicate it as well or it’s emulator specific?

Thanks!

**Comment by carmiker** [comment]
The "freeze" is separate from the typical green garbage output at bootup on the MVS. That refers to being stuck there, on the green screen, forever. This is just normal behaviour, it's just how the System ROM looks when it boots. It's the same on real hardware.
